logging:
  level:
    ROOT: INFO

spring:
  application:
    name: pricing
  datasource:
    url: # set JDBC URL of the database
    username: # set login username of the database
    password: # set login password of the database
  flyway:
    locations: classpath:/db/migrations
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
